Loading configuration... done.
['Simulation.py', '40', '35', '20', '10']
Could not connect to TraCI server at localhost:55617 [Errno 111] Connection refused
 Retrying in 1 seconds
{'wait_time': [0, 72.26164506490828, 18.263596499976853, 31.626631672028136, 81.13039847917618]}
